#加密配置
#jasypt:
#  encryptor:
#    password: lengleng

server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads

spring:
  redis:
    remote: false        #cachecloud 获取
    host: 127.0.0.1
    port: 6379
    password:
    
  datasource:
    url: jdbc:mysql://localhost:3306/self_omp
    username: root
    password: 123456
    
    data:
      url: jdbc:mysql://localhost:3306/jims-his
      username: root
      password: 123456
      
 eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@localhost:1025/eureka
    registry-fetch-interval-seconds: 10
