#加密配置
#jasypt:
#  encryptor:
#    password: lengleng

server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads

spring:
  redis:
    remote: false        #cachecloud 获取
    host: 127.0.0.1
    port: 6379
    password:
    
 spring:
  datasource:
    url: jdbc:mysql://localhost:3306/self_omp
    username: root
    password: 123456
    
    data:
      url: jdbc:mysql://localhost:3306/jims-his
      username: root
      password: 123456
