server:
  port: 9999

spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2

zuul:
  ribbon:
    eager-load:
      enabled: true
      clients: mcp-auth,mcp-upms-service
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    mcp-auth:
      path: /auth/**
      serviceId: mcp-auth
      stripPrefix: true
      sensitiveHeaders:
    mcp-upms-service:
      path: /admin/**
      serviceId: mcp-upms-service
      stripPrefix: true
      sensitiveHeaders:
  ratelimit:
    key-prefix: mcp-ratelimite
    enabled: true
    repository: REDIS
    behind-proxy: true
    policies:
      mcp-upms-service:
        limit: 100
        quota: 100
        refresh-interval: 3

security:
  validate:
    code: true
    preview: true
  sessions: stateless
  oauth2:
    client:
      client-id: mcp
      client-secret: mcp
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check-token
      service-id: mcp-gateway
      jwt:
         key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址

urls:
  anon:
    - /mobile/**
    - /auth/**
    - /admin/code/*
    - /admin/smsCode/*
    - /admin/user/info
    - /admin/menu/userTree
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**