
#
#spring.resources.static-locations=file:E:/images

# datasoure默认使用JDBC

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/self_omp
    username: root
    password: 123456
    
    data:
      url: jdbc:mysql://localhost:3306/jims-his
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@eureka:1025/eureka





