server:
  port: 4060
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/pig
  elasticjob:
    zookeeper:
      server-lists: 127.0.0.1:2181
      namespace: mcp-daemon
